#include "NavigationWorkspace.h"
#include <algorithm>
#include <cwctype>
#include <filesystem>
#include <fstream>
#include <regex>
#include <sstream>
#include <shlobj.h>
#include <windows.h>
namespace ffui { namespace {
constexpr size_t kMaxRecentlyClosedTabs = 16;
bool IsAbsolutePath(const std::wstring& path) { return (path.size() >= 3 && std::iswalpha(path[0]) && path[1] == L':' && path[2] == L'\\') || (path.size() >= 3 && path[0] == L'\\' && path[1] == L'\\' && path[2] != L'\\'); }
std::wstring DefaultBookmarkName(const std::wstring& path) { const size_t end = path.find_last_not_of(L'\\'); const size_t slash = path.find_last_of(L'\\', end); return slash == std::wstring::npos ? path : path.substr(slash + 1, end - slash); }
std::wstring EscapeJson(const std::wstring& value) { std::wstring result; for (wchar_t ch : value) { if (ch == L'"' || ch == L'\\') result += L'\\'; if (ch == L'\n') result += L"\\n"; else if (ch == L'\r') result += L"\\r"; else if (ch == L'\t') result += L"\\t"; else result += ch; } return result; }
std::wstring UnescapeJson(const std::wstring& value) { std::wstring result; for (size_t i = 0; i < value.size(); ++i) { if (value[i] != L'\\' || i + 1 == value.size()) { result += value[i]; continue; } const wchar_t escaped = value[++i]; result += escaped == L'n' ? L'\n' : escaped == L'r' ? L'\r' : escaped == L't' ? L'\t' : escaped; } return result; }
bool ReadBoolean(const std::wstring& json, const wchar_t* name) { std::wregex expression(std::wstring(L"\"") + name + L"\"\\s*:\\s*(true|false)"); std::wsmatch match; return std::regex_search(json, match, expression) && match[1] == L"true"; }
} // namespace
NavigationContext NavigationWorkspace::MakeContext(const std::wstring& path) { NavigationContext r; r.currentPath = path; r.history.push_back(path); return r; }
NavigationWorkspace::NavigationWorkspace(std::wstring defaultPath) : defaultPath_(std::move(defaultPath)) { tabs_.push_back({{MakeContext(defaultPath_)}, 0}); LoadState(state_); }
NavigationWorkspace::Tab& NavigationWorkspace::ActiveTab() { return tabs_[activeTab_]; } const NavigationWorkspace::Tab& NavigationWorkspace::ActiveTab() const { return tabs_[activeTab_]; }
NavigationContext& NavigationWorkspace::ActiveContext() { return ActiveTab().panes[ActiveTab().activePane]; } const NavigationContext& NavigationWorkspace::ActiveContext() const { return ActiveTab().panes[ActiveTab().activePane]; }
bool NavigationWorkspace::IsDualPane() const { return ActiveTab().panes.size() == 2; } bool NavigationWorkspace::CanGoBack() const { return ActiveContext().historyIndex > 0; } bool NavigationWorkspace::CanGoForward() const { return ActiveContext().historyIndex + 1 < ActiveContext().history.size(); }
void NavigationWorkspace::Navigate(const std::wstring& path) { auto& c = ActiveContext(); if (path == c.currentPath) return; c.history.resize(c.historyIndex + 1); c.history.push_back(path); c.historyIndex = c.history.size() - 1; c.currentPath = path; c.addressBarMode = AddressBarMode::Breadcrumb; c.addressBarError.clear(); }
bool NavigationWorkspace::GoBack() { if (!CanGoBack()) return false; auto& c = ActiveContext(); c.currentPath = c.history[--c.historyIndex]; return true; } bool NavigationWorkspace::GoForward() { if (!CanGoForward()) return false; auto& c = ActiveContext(); c.currentPath = c.history[++c.historyIndex]; return true; }
std::vector<BreadcrumbSegment> NavigationWorkspace::Breadcrumbs() const { const std::wstring& path = ActiveContext().currentPath; std::vector<BreadcrumbSegment> result; result.push_back({L"This PC", L""}); if (path.size() >= 3 && path[1] == L':' && path[2] == L'\\') { std::wstring accumulated = path.substr(0, 3); result.push_back({path.substr(0, 2), accumulated}); size_t start = 3; while (start < path.size()) { const size_t end = path.find(L'\\', start); const std::wstring component = path.substr(start, end == std::wstring::npos ? std::wstring::npos : end - start); if (!component.empty()) { if (accumulated.back() != L'\\') accumulated += L'\\'; accumulated += component; result.push_back({component, accumulated}); } if (end == std::wstring::npos) break; start = end + 1; } return result; } if (path.rfind(L"\\\\", 0) == 0) { std::wstring accumulated = L"\\\\"; size_t start = 2; while (start < path.size()) { const size_t end = path.find(L'\\', start); const std::wstring component = path.substr(start, end == std::wstring::npos ? std::wstring::npos : end - start); if (!component.empty()) { accumulated += component; result.push_back({component, accumulated}); accumulated += L'\\'; } if (end == std::wstring::npos) break; start = end + 1; } } return result; }
void NavigationWorkspace::BeginAddressBarEdit() { auto& context = ActiveContext(); context.addressBarMode = AddressBarMode::EditableText; context.addressBarText = context.currentPath; context.addressBarError.clear(); }
void NavigationWorkspace::CancelAddressBarEdit() { auto& context = ActiveContext(); context.addressBarMode = AddressBarMode::Breadcrumb; context.addressBarText.clear(); context.addressBarError.clear(); }
bool NavigationWorkspace::NavigateBreadcrumb(size_t segmentIndex) { const auto segments = Breadcrumbs(); if (segmentIndex >= segments.size() || segments[segmentIndex].path.empty()) return false; Navigate(segments[segmentIndex].path); return true; }
void NavigationWorkspace::OpenTab(const std::optional<std::wstring>& path) { tabs_.push_back({{MakeContext(path.value_or(ActiveContext().currentPath))}, 0}); activeTab_ = tabs_.size() - 1; }
bool NavigationWorkspace::CloseActiveTab() { if (tabs_.size() == 1) return false; state_.recentlyClosedTabs.push_front(ActiveContext().currentPath); if (state_.recentlyClosedTabs.size() > kMaxRecentlyClosedTabs) state_.recentlyClosedTabs.pop_back(); tabs_.erase(tabs_.begin() + static_cast<std::ptrdiff_t>(activeTab_)); activeTab_ = std::min(activeTab_, tabs_.size() - 1); SaveState(state_); return true; }
bool NavigationWorkspace::SwitchTab(size_t index) { if (index >= tabs_.size()) return false; activeTab_ = index; return true; } bool NavigationWorkspace::ReopenClosedTab() { if (state_.recentlyClosedTabs.empty()) return false; auto path = state_.recentlyClosedTabs.front(); state_.recentlyClosedTabs.pop_front(); OpenTab(path); SaveState(state_); return true; }
void NavigationWorkspace::EnableDualPane() { if (!IsDualPane()) ActiveTab().panes.push_back(MakeContext(ActiveContext().currentPath)); } void NavigationWorkspace::DisableDualPane() { auto& t = ActiveTab(); if (!IsDualPane()) return; auto kept = t.panes[t.activePane]; t.panes = {std::move(kept)}; t.activePane = 0; } void NavigationWorkspace::ActivatePane(size_t index) { if (index < ActiveTab().panes.size()) ActiveTab().activePane = index; }
void NavigationWorkspace::AddBookmark(const std::wstring& path, std::wstring name) { state_.bookmarks.push_back({path, name.empty() ? DefaultBookmarkName(path) : std::move(name)}); SaveState(state_); } bool NavigationWorkspace::RenameBookmark(size_t index, const std::wstring& name) { if (index >= state_.bookmarks.size() || name.empty()) return false; state_.bookmarks[index].displayName = name; SaveState(state_); return true; } bool NavigationWorkspace::ReorderBookmark(size_t from, size_t to) { if (from >= state_.bookmarks.size() || to >= state_.bookmarks.size()) return false; auto v = state_.bookmarks[from]; state_.bookmarks.erase(state_.bookmarks.begin() + static_cast<std::ptrdiff_t>(from)); state_.bookmarks.insert(state_.bookmarks.begin() + static_cast<std::ptrdiff_t>(to), std::move(v)); SaveState(state_); return true; } bool NavigationWorkspace::RemoveBookmark(size_t index) { if (index >= state_.bookmarks.size()) return false; state_.bookmarks.erase(state_.bookmarks.begin() + static_cast<std::ptrdiff_t>(index)); SaveState(state_); return true; }
std::vector<std::wstring> NavigationWorkspace::EnumerateDrives() { std::vector<std::wstring> r; DWORD mask = GetLogicalDrives(); for (wchar_t c = L'A'; c <= L'Z'; ++c) if (mask & (1u << (c - L'A'))) r.push_back(std::wstring(1, c) + L":\\"); return r; }
std::vector<Bookmark> NavigationWorkspace::EnumerateKnownFolders() { struct F { const wchar_t* n; const KNOWNFOLDERID* id; } f[] = {{L"Desktop", &FOLDERID_Desktop}, {L"Documents", &FOLDERID_Documents}, {L"Downloads", &FOLDERID_Downloads}, {L"Pictures", &FOLDERID_Pictures}, {L"Videos", &FOLDERID_Videos}, {L"Music", &FOLDERID_Music}}; std::vector<Bookmark> r; for (const auto& x : f) { PWSTR p = nullptr; HRESULT h = SHGetKnownFolderPath(*x.id, KF_FLAG_DEFAULT, nullptr, &p); r.push_back({h == S_OK ? p : L"", x.n}); if (p) CoTaskMemFree(p); } return r; }
std::wstring NavigationWorkspace::StateFilePath() { wchar_t buffer[MAX_PATH]; const DWORD length = GetEnvironmentVariableW(L"LOCALAPPDATA", buffer, MAX_PATH); return length == 0 || length >= MAX_PATH ? L"" : std::wstring(buffer) + L"\\FastFiles\\workspace-state.json"; }
bool NavigationWorkspace::LoadState(WorkspaceState& state) { state = {}; const std::wstring file = StateFilePath(); if (file.empty()) return false; std::wifstream input(file); if (!input) return true; std::wstringstream buffer; buffer << input.rdbuf(); const std::wstring json = buffer.str(); try { if (!std::regex_search(json, std::wregex(L"\"version\"\\s*:\\s*1"))) return true; state.sidebarCollapsed = ReadBoolean(json, L"sidebarCollapsed"); state.drivesCollapsed = ReadBoolean(json, L"drivesCollapsed"); state.knownFoldersCollapsed = ReadBoolean(json, L"knownFoldersCollapsed"); state.bookmarksCollapsed = ReadBoolean(json, L"bookmarksCollapsed"); const std::wregex bookmark(L"\\{\\s*\"path\"\\s*:\\s*\"((?:\\\\.|[^\"])*)\"\\s*,\\s*\"displayName\"\\s*:\\s*\"((?:\\\\.|[^\"])*)\"\\s*\\}"); for (std::wsregex_iterator i(json.begin(), json.end(), bookmark), end; i != end; ++i) state.bookmarks.push_back({UnescapeJson((*i)[1]), UnescapeJson((*i)[2])}); const std::wregex closed(L"\"recentlyClosedTabs\"\\s*:\\s*\\[([^]]*)\\]"); std::wsmatch closedArray; if (std::regex_search(json, closedArray, closed)) { const std::wregex string(L"\"((?:\\\\.|[^\"])*)\""); for (std::wsregex_iterator i(closedArray[1].first, closedArray[1].second, string), end; i != end; ++i) state.recentlyClosedTabs.push_back(UnescapeJson((*i)[1])); } } catch (const std::regex_error&) { state = {}; } return true; }
bool NavigationWorkspace::SaveState(const WorkspaceState& state) { const std::wstring file = StateFilePath(); if (file.empty()) return false; std::error_code error; std::filesystem::create_directories(std::filesystem::path(file).parent_path(), error); if (error) return false; std::wofstream output(file, std::ios::trunc); if (!output) return false; output << L"{\n  \"version\": 1,\n  \"sidebarCollapsed\": " << (state.sidebarCollapsed ? L"true" : L"false") << L",\n  \"drivesCollapsed\": " << (state.drivesCollapsed ? L"true" : L"false") << L",\n  \"knownFoldersCollapsed\": " << (state.knownFoldersCollapsed ? L"true" : L"false") << L",\n  \"bookmarksCollapsed\": " << (state.bookmarksCollapsed ? L"true" : L"false") << L",\n  \"bookmarks\": ["; for (size_t i = 0; i < state.bookmarks.size(); ++i) { const auto& bookmark = state.bookmarks[i]; output << (i ? L"," : L"") << L"\n    {\"path\": \"" << EscapeJson(bookmark.path) << L"\", \"displayName\": \"" << EscapeJson(bookmark.displayName) << L"\"}"; } output << L"\n  ],\n  \"recentlyClosedTabs\": ["; for (size_t i = 0; i < state.recentlyClosedTabs.size(); ++i) output << (i ? L", " : L"") << L"\"" << EscapeJson(state.recentlyClosedTabs[i]) << L"\""; output << L"]\n}\n"; return static_cast<bool>(output); }
ParsedPath ParseNavigationPath(const std::wstring& input) { auto first = input.find_first_not_of(L" \t\r\n"); auto last = input.find_last_not_of(L" \t\r\n"); if (first == std::wstring::npos) return {{}, L"Enter an absolute path."}; std::wstring v = input.substr(first, last - first + 1); if (v.size() >= 2 && v.front() == L'"' && v.back() == L'"') v = v.substr(1, v.size() - 2); std::replace(v.begin(), v.end(), L'/', L'\\'); DWORD needed = ExpandEnvironmentStringsW(v.c_str(), nullptr, 0); if (needed) { std::wstring e(needed, L'\0'); ExpandEnvironmentStringsW(v.c_str(), e.data(), needed); e.pop_back(); v = std::move(e); } if (!IsAbsolutePath(v)) return {{}, L"Paths must begin with a drive or UNC root."}; if (v.find_first_of(L"<>|?*") != std::wstring::npos) return {{}, L"The path contains reserved characters."}; std::wstring full(32768, L'\0'); DWORD size = GetFullPathNameW(v.c_str(), static_cast<DWORD>(full.size()), full.data(), nullptr); if (!size || size >= full.size()) return {{}, L"The path is invalid."}; full.resize(size); while (full.size() > 3 && full.back() == L'\\') full.pop_back(); return {std::move(full), {}}; }
PathCommitResult CommitAddressBarPath(NavigationWorkspace& workspace, const std::wstring& input) { auto parsed = ParseNavigationPath(input); auto& c = workspace.ActiveContext(); if (!parsed.error.empty()) { c.addressBarError = parsed.error; c.addressBarMode = AddressBarMode::EditableText; return PathCommitResult::Invalid; } if (GetFileAttributesW(parsed.path.c_str()) == INVALID_FILE_ATTRIBUTES) { c.addressBarError = L"This location no longer exists."; c.addressBarMode = AddressBarMode::EditableText; return PathCommitResult::NotFound; } workspace.Navigate(parsed.path); return PathCommitResult::Navigated; }
} // namespace ffui
